import { parse } from 'cookie'
import { Redis } from '@upstash/redis'
import { v4 as uuidv4 } from 'uuid'
import crypto from 'crypto'

const redis = new Redis({
  url: process.env.UPSTASH_REDIS_REST_URL,
  token: process.env.UPSTASH_REDIS_REST_TOKEN,
})

const corsHeaders = {
  'Access-Control-Allow-Origin': process.env.FRONTEND_URL || '*',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization',
  'Access-Control-Allow-Credentials': 'true'
}

// Removed Claude API key functions - Ollama only

function getOllamaCredentials(password = null) {
  const username = process.env.OLLAMA_USERNAME
  const token = process.env.OLLAMA_PASSWORD
  const encryptedToken = process.env.OLLAMA_PASSWORD_ENCRYPTED
  
  if (encryptedToken && password) {
    try {
      const parts = encryptedToken.split(':')
      if (parts.length !== 3) return null
      
      const key = crypto.scryptSync(password, 'salt', 32)
      const iv = Buffer.from(parts[0], 'hex')
      const authTag = Buffer.from(parts[1], 'hex')
      const encrypted = parts[2]
      
      const decipher = crypto.createDecipherGCM('aes-256-gcm', key, iv)
      decipher.setAuthTag(authTag)
      let decrypted = decipher.update(encrypted, 'hex', 'utf8')
      decrypted += decipher.final('utf8')
      return { username, token: decrypted }
    } catch (error) {
      console.error('Failed to decrypt Ollama token')
      return null
    }
  }
  
  return { username, token }
}

async function processJob(jobId, jobData, userPassword = null) {
  try {
    console.log('Processing Ollama job:', jobId)

    // Update status to processing
    await redis.hset(`job:${jobId}`, {
      status: 'processing',
      updatedAt: Date.now()
    })

    const { payload } = jobData

    // Handle Ollama models only
    const credentials = getOllamaCredentials(userPassword)
    if (!credentials || !credentials.username || !credentials.token) {
      throw new Error('Ollama credentials not available')
    }

    const authHeader = Buffer.from(`${credentials.username}:${credentials.token}`).toString('base64')
    const ollamaUrl = process.env.OLLAMA_URL || 'https://roo.ai.hypha.coop/api/generate'

    const ollamaResponse = await fetch(ollamaUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Basic ${authHeader}`
      },
      body: JSON.stringify({
        model: payload.model,
        prompt: payload.messages[0].content,
        stream: false,
        options: {
          num_predict: payload.max_tokens || 5000
        }
      })
    })

    if (!ollamaResponse.ok) {
      throw new Error(`Ollama API error: ${ollamaResponse.status} ${ollamaResponse.statusText}`)
    }

    const ollamaData = await ollamaResponse.json()
    const generatedBylaws = ollamaData.response

    console.log('Generated bylaws length:', generatedBylaws.length)

    await redis.hset(`job:${jobId}`, {
      status: 'completed',
      result: generatedBylaws,
      completedAt: Date.now()
    })

    // Set expiration for 24 hours
    await redis.expire(`job:${jobId}`, 86400)

    console.log('Job completed successfully:', jobId)
    return true

  } catch (error) {
    console.error('Job processing error:', error)

    // Mark job as failed
    await redis.hset(`job:${jobId}`, {
      status: 'failed',
      error: error.message,
      failedAt: Date.now()
    })

    return false
  }
}

function requireAuth(req) {
  try {
    const cookies = parse(req.headers.cookie || '')
    const sessionToken = cookies['auth-session']
    
    if (!sessionToken) {
      return { authenticated: false, error: 'No session token' }
    }

    const sessionData = JSON.parse(Buffer.from(sessionToken, 'base64').toString())
    
    // Check if session is expired (24 hours)
    const isExpired = Date.now() - sessionData.timestamp > 24 * 60 * 60 * 1000
    
    if (isExpired || !sessionData.authenticated) {
      return { authenticated: false, error: 'Session expired' }
    }

    return { authenticated: true, password: sessionData.password }
  } catch (error) {
    return { authenticated: false, error: 'Invalid session' }
  }
}

export default async function handler(req, res) {
  // Handle CORS preflight
  if (req.method === 'OPTIONS') {
    return res.status(200)
      .setHeader('Access-Control-Allow-Origin', corsHeaders['Access-Control-Allow-Origin'])
      .setHeader('Access-Control-Allow-Methods', corsHeaders['Access-Control-Allow-Methods'])
      .setHeader('Access-Control-Allow-Headers', corsHeaders['Access-Control-Allow-Headers'])
      .setHeader('Access-Control-Allow-Credentials', corsHeaders['Access-Control-Allow-Credentials'])
      .end()
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' })
  }

  // Set CORS headers
  res.setHeader('Access-Control-Allow-Origin', corsHeaders['Access-Control-Allow-Origin'])
  res.setHeader('Access-Control-Allow-Credentials', 'true')

  // Check authentication
  const auth = requireAuth(req)
  if (!auth.authenticated) {
    return res.status(401).json({ error: 'Authentication required', detail: auth.error })
  }

  try {
    // Generate unique job ID
    const jobId = uuidv4()

    console.log('Submitting Ollama job:', jobId)

    // Store initial job data
    await redis.hset(`job:${jobId}`, {
      status: 'queued',
      jobData: JSON.stringify(req.body),
      createdAt: Date.now()
    })

    // Process the job directly (await completion)
    console.log('Starting direct processing for job:', jobId)
    await processJob(jobId, req.body, auth.password)

    return res.status(202).json({ 
      jobId,
      status: 'queued',
      message: 'Job submitted and processing started.'
    })

  } catch (error) {
    console.error('Job submission error:', error)
    return res.status(500).json({ 
      error: 'Failed to submit job', 
      detail: error.message 
    })
  }
} 